---
title           : "Historical trends in ice cover for Wisconsin Lakes
Mendota and Menonoa"
shorttitle      : "Trends in ice cover"
date            : "`r Sys.setlocale('LC_TIME', 'C'); format(Sys.time(), '%d\\\\. %B %Y')`"

author: 
  - name        : David R. Zilkey
    affiliation : 1, 2


affiliation:
  - id          : 1
    institution : McGill University
  - id          : 2
    institution : Groupe de Recherche Interuniversitaire en Limnologie

output: prereg::prereg_pdf
---

<!-- To keep pre-registrations to a reasonable length for readers, we recommend answers fit within a single page .pdf document, roughly 3200 characters. Read more about this here: https://aspredicted.org/messages/why_limits.php -->


## Data collection
<!-- Have any data been collected for this study already? (Note: "Yes" is not an accepted answer.) -->
**Yes**, we already collected the data.


## Hypothesis
<!-- What's the main question being asked or hypothesis being tested in this study? -->
>What are the long-term trends in ice cover on Lakes Mendonta and Menonoa? Do trends differ between
the two lakes?



## Dependent variable
<!-- Describe the key dependent variable(s) specifying how they will be measured. -->
> The dependent variables are ice in date, ice out date, and number of ice covered days.


## Conditions
<!-- How many and which conditions will participants be assigned to? -->
>Lakes will be assigned a condition on each day of measurement - ice covered or uncovered.


## Analyses
<!-- Specify exactly which analyses you will conduct to examine the main question/hypothesis. -->
>As we expect the trends in ice cover over time to be nonlinear, we will use generalized additive models (GAM) to
characterize trends. 


## Outliers and exclusions
<!-- Describe exactly how outliers will be defined and handled, and your precise rule(s) for excluding observations. -->
>We will not exclude outliers but will ensure that GAM fits are not overly influenced by them so as to over fit and falsely conclude
that a trend exists in ice cover over time.


## Sample size
<!-- How many observations will be collected or what will determine sample size? No need to justify decision, but be precise about _exactly_ how the number will be determined. -->
>Sample size is pre-determined by the start date of monitoring (1853 CE for Lake Mendota, 
1851 CE for Lake Menonoa)

## Other
<!-- Anything else you would like to pre-register? (e.g., secondary analyses, variables collected for exploratory purposes, unusual analyses planned?) -->
>Nothing else to declare.

## Study type
*Class project or assignment



# References
## 
\vspace{-2pc}
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{-1in}
\setlength{\parskip}{8pt}
\noindent
